name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'

env:
    LOCATION: eastus2
    RESOURCE_GROUP: nov

jobs:
    cache-and-install:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest # You can also use a specific version

            - name: Get bun store directory
              run: echo "STORE_PATH=$(~/.bun/install/cache)" >> $GITHUB_ENV

            - name: Cache bun modules
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.bun/install/cache
                      ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun-lockb') }} # Note: adjust the lock file if it's different for bun
                  restore-keys: ${{ runner.os }}-bun-

            - name: Install dependencies
              run: bun install --frozen-lockfile

    lint-and-static-analysis:
        needs: cache-and-install
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest # You can also use a specific version

            - name: Get bun store directory
              run: echo "STORE_PATH=$(~/.bun/install/cache)" >> $GITHUB_ENV

            - name: Cache bun modules
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.bun/install/cache
                      ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun-lockb') }} # Note: adjust the lock file if it's different for bun
                  restore-keys: ${{ runner.os }}-bun-

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Lint the project
              run: bun run lint

    test:
        needs: lint-and-static-analysis
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest # You can also use a specific version

            - name: Get bun store directory
              run: echo "STORE_PATH=$(~/.bun/install/cache)" >> $GITHUB_ENV

            - name: Cache bun modules
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.bun/install/cache
                      ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun-lockb') }} # Note: adjust the lock file if it's different for bun
                  restore-keys: ${{ runner.os }}-bun-

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Run tests
              run: bun run test

    build-app:
        needs: test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest # You can also use a specific version

            - name: Get bun store directory
              run: echo "STORE_PATH=$(~/.bun/install/cache)" >> $GITHUB_ENV

            - name: Cache bun modules
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.bun/install/cache
                      ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun-lockb') }} # Note: adjust the lock file if it's different for bun
                  restore-keys: ${{ runner.os }}-bun-

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Build the app
              run: bun run build

    provision:
        name: Provision resources
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}
            - name: Ensure resource group exists
              uses: azure/CLI@v1
              with:
                  inlineScript: az group create -g ${{ env.RESOURCE_GROUP }} -l ${{ env.LOCATION }}
            - name: Provision resources
              if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
              uses: azure/arm-deploy@v1
              with:
                  resourceGroupName: ${{ env.RESOURCE_GROUP }}
                  template: ./main.bicep
                  parameters: location=${{ env.LOCATION }}

    deploy:
        name: Deploy
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'repository_dispatch'
        needs: provision
        strategy:
            matrix:
                app: [web]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}
            - name: Get deployment token
              uses: azure/CLI@v1
              id: swa-token
              with:
                  inlineScript: |
                      SWA_DEPLOYMENT_TOKEN=$(az staticwebapp secrets list -n ${{ env.RESOURCE_GROUP }}-${{ matrix.app }} -o tsv --query properties.apiKey)
                      echo "::add-mask::$SWA_DEPLOYMENT_TOKEN"
                      echo SWA_DEPLOYMENT_TOKEN=$SWA_DEPLOYMENT_TOKEN >> $GITHUB_ENV
            - name: Deploy app
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ env.SWA_DEPLOYMENT_TOKEN }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  action: 'upload'
                  app_location: apps/${{ matrix.app }}
                  output_location: dist

    undeploy_previews:
        name: Undeploy preview
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        needs: provision
        strategy:
            matrix:
                app: [cms, web]
        runs-on: ubuntu-latest
        steps:
            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}
            - name: Get deployment token
              uses: azure/CLI@v1
              id: swa-token
              with:
                  inlineScript: |
                      SWA_DEPLOYMENT_TOKEN=$(az staticwebapp secrets list -n ${{ env.RESOURCE_GROUP }}-${{ matrix.app }} -o tsv --query properties.apiKey)
                      echo "::add-mask::$SWA_DEPLOYMENT_TOKEN"
                      echo SWA_DEPLOYMENT_TOKEN=$SWA_DEPLOYMENT_TOKEN >> $GITHUB_ENV
            - name: Undeploy app
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ env.SWA_DEPLOYMENT_TOKEN }}
                  action: 'close'
